/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      /* ============================================================
       * Design Tokens — Extracted from Stitch Mockups
       * Material Design 3 color system with custom palette
       * ============================================================ */
      colors: {
        "tertiary": "#006c49",
        "on-surface-variant": "#464554",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#005236",
        "primary-fixed-dim": "#c0c1ff",
        "outline": "#767586",
        "surface-variant": "#e0e3e5",
        "secondary": "#006591",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        "error": "#ba1a1a",
        "on-tertiary-container": "#000703",
        "secondary-fixed-dim": "#89ceff",
        "inverse-on-surface": "#eff1f3",
        "surface": "#f7f9fb",
        "primary": "#4648d4",
        "on-surface": "#191c1e",
        "secondary-fixed": "#c9e6ff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary-container": "#39b8fd",
        "on-secondary-container": "#004666",
        "inverse-primary": "#c0c1ff",
        "on-primary": "#ffffff",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed": "#001e2f",
        "surface-tint": "#494bd6",
        "tertiary-fixed": "#6ffbbe",
        "primary-container": "#6063ee",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#c7c4d7",
        "on-primary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#004c6e",
        "tertiary-fixed-dim": "#4edea3",
        "surface-bright": "#f7f9fb",
        "tertiary-container": "#00885d",
        "on-tertiary-fixed": "#002113",
        "primary-fixed": "#e1e0ff",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fffbff",
        "background": "#f7f9fb",
        "error-container": "#ffdad6",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
